version: "3.7"
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_STACK_VERSION}
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ES_PASSWORD}
    mem_limit: ${ES_MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - elasticsearchdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:${ES_STACK_VERSION}
    restart: always
    environment:
      SERVERNAME: kibana
      ELASTICSEARCH_HOSTS: http://es:9200 # address of elasticsearch docker container which kibana will connect
      ELASTICSEARCH_USERNAME: kibana_system
      ELASTICSEARCH_PASSWORD: ${KIBANA_PASSWORD}
    ports:
      - 5601:5601
    depends_on:
      - es # kibana will start when elasticsearch has started
    volumes:
      - kibanadata:/usr/share/kibana/data

  salary-survey-server:
    build:
      context: salary_api
      dockerfile: Dockerfile
    ports:
      - 5001:5000
    environment:
      FLASK_APP: main.py
      FLASK_ENV: development
      FLASK_DEBUG: 1
      ELASTICSEARCH_URL: ${ELASTICSEARCH_URL}
    command: pipenv run runserver
    depends_on:
      - es
volumes:
  elasticsearchdata:
  kibanadata:
