# black setup.cfg

[tool.black]
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.mypy_cache
    | \.pytest_cache
    | \.venv
    | __pychache__
    | migrations
  )/
)
'''

[tool.autoflake]
check = true
